

[TOC]

# 异常的概述

1. 在java程序《运行》过程中，出现的不正常情况，出现的错误，称为异常
2. 异常就是一个对象，描述那些不符合生活正常情况的异常情况，包含了这些情况的原因、类型、描述以及位置，这些内容都封装到异常对象中。
3. 异常也是一种处理异常情况的机制，可以进行跳转、捕获以及结束程序

# 异常的体系

1. Throwable：可抛出的，是异常体系的顶层父类，其它的异常或者错误都是Throwable的子类类型，

     只有Throwable的体系类型，才可以使用异常的处理机制

2. Error：错误，是Throwable的子类，用于描述那些无法捕获和处理的错误情况，属于非常严重的错误，

     1. StackOverflowError

3. Exception：异常，是Throwable的子类，用于描述那些可以捕获和处理的例外情况，属于不太严重的错误，

     1. ArrayIndexOutOfBoundsException

4. RuntimeException：运行时异常，是Exception的特殊的子类，在编译阶段不做检查的一个异常，

     这种异常我们不需要处理，由虚拟机掌管，

     1. NullPointerException

5. 体系图：			

     ![image-20230801164412943](https://s2.loli.net/2023/08/01/d74nLXYHyb1cGNl.png)

# jvm默认处理异常的机制

5. 总结，jvm默认处理的方式：【一层一层向上抛，jvm接收到之后结束自己】

代码示例：

```java
/**
 * 在jvm中 默认处理异常的机制
 */
public class Simple01 {

    public static void main(String[] args) {
        test1();
    }

    private static void test1() {
        test2();
    }

    private static void test2() {
        test3();
    }

    private static void test3() {
        int i = 1 / 0;
        System.out.println(i);
    }
}
```

## 手动处理异常的方式

1. 有两大类处理异常的方式：
    	异常的声明：某个方法有编译时异常，编译就会无法通过，需要在异常所在的方法声明上，声明该方法可能出现的编译时异常
     异常的**捕获**：可以通过某些格式来捕获异常，可以让程序在出现异常之后，继续运行。可以定义自己处理异常的逻辑。

## 异常捕获的第一种格式

1、格式：
 try {
     	可能发生异常的代码
} catch(可能出现异常的类型 标识符) {
 	这种异常出现之后的处理方式
}
2、try语句块中，是可能会运行失败的代码，try语句是用于对异常进行检测
3、catch：抓住、捕获
 	抓住try语句中出现的异常，并且定义异常处理的方式
4、运行机制：
 	1、运行try语句中的代码
 	2、如果没有发生任何异常，那么不再运行catch块中的内容
 	3、如果发生了catch中声明的异常，那么就会被捕获到这个异常，执行catch块中的内容（try中如果发生了异常，try中，该语句后面的代码都无法执行了，直接跳到catch中）
  	4、如果发生了catch中没有声明的异常，那么就无法捕获该异常，该异常的处理就使用jvm的默认处理方式
代码示例：

```java
import java.util.Scanner;

/**
 * 异常捕获的第一种格式
 */
public class Simple02 {
    public static void main(String[] args) {
        test1();
    }

    private static void test1() {
        test2();
    }

    private static void test2() {
        test3();
    }

    private static void test3() {
        Scanner sc = new Scanner(System.in);
        System.out.println("请录入一个除数");
        try {
            int i = 100 / sc.nextInt();
            System.out.println(i);
	          //int[] arr = null;
						//System.out.println(arr.length);
        } catch (ArithmeticException ae) {
            System.out.println("除零异常发生了，请重新运行程序，输入正确的除数");
        }
        System.out.println("异常没有发生或者处理结束了");
    }
}
```

## 异常捕获的第一种格式其它情况

1、在一段代码中，可能出现多种异常（虽然一次运行只能出现一个异常，但是出现哪个异常我们是不清楚的），所以要准备多种异常情况的处理机制。
2、格式：
 	try {
 	 	可能出现异常的代码
} catch (异常类型1  异常对象名1) {
 	异常类型1出现之后的处理办法
} catch (异常类型2  异常对象名2) {
 	异常类型2出现之后的处理办法
}
....
} catch (异常类型n 异常对象名n) {
 	异常类型n出现之后的处理办法
}
3、执行流程：
 	1、执行try中的内容，如果没有异常，try...catch语句直接结束
 	2、如果有异常，那么就在发生异常的代码位置直接跳转到catch块中，try中后面的代码就不再继续运行了
 	3、继续匹配各个catch块中的异常类型，从上到下，一旦匹配到某个catch声明的异常类型，就直接执行该catch块的处理方式。处理完成之后，try...catch语句就直接结束了，不会再去匹配后面其他的catch块的异常类型
4、注意事项： 	
 	1、如果在各个catch块中，出现了子父类的异常类型，那么子类异常的catch块，必须在父类异常catch块的上面，因为从上到下匹配方式，如果父类的catch块在上面，下面的catch块就没有出现的意义了，无法到达的代码。
 	2、在jdk1.7之后，可以对异常类型进行逻辑的或运算，使用|表示，多种异常类型，可以使用相同的处理方式：
 		catch(异常类型1 | 异常类型2  异常对象名称) {
 	 	 	异常类型1和2的共同处理方式
}

代码示例：

```java
import java.util.Scanner;

/**
 * 异常捕获的第一种格式的多种异常情况
 */
public class Simple03 {
    public static void main(String[] args) {

        Scanner sc = new Scanner(System.in);
        try {
            System.out.println("请录入一个除数");
            int x = sc.nextInt();
            int i = 10 / x;
            System.out.println(i);

            int[] arr = {1, 2, 3, 4, 5};
            System.out.println("请录入一个要访问的索引");
            int y = sc.nextInt();
            System.out.println(arr[y]);

            arr = null;
            System.out.println(arr.length);
        } /*catch (Exception e) {
         System.out.println("异常发生了");//父类引用放到子类型下方
        }*/ catch (ArithmeticException ae) {
            System.out.println("除零异常发生了");
        } catch (ArrayIndexOutOfBoundsException be) {
            System.out.println("索引越界异常发生了");
        } catch (NullPointerException npe) {
            System.out.println("空指针异常发生了");
        }
     /*   catch (ArrayIndexOutOfBoundsException | NullPointerException ane) {
            System.out.println("数组操作出现异常");
        }*/
        System.out.println("异常已经被处理或者没有异常");
    }
}
```

## 异常捕获的第二种格式

1、格式：
 	try {
 	 	可能发生异常的代码
 	} catch (可能发生的异常类型  异常对象名称) {
 	 	当前异常类型的处理方式
} finally {
 	一定要执行的代码
}
2、finally：一定要执行的代码
 	1、如果把某句代码放在try中，可能在这句话前面有异常，那么这句话就无法执行；如果把某句代码放在catch中，有可能try中没有异常，就无法执行这句话；如果把某句代码放在try...catch之后，可能有未捕获的异常，那么这句代码也无法执行。
 	2、finally：也是一个代码块，在这个代码块中的代码，一定会执行，无论上面描述的哪种情况，都会执行。甚至在代码中有return语句，都会先执行finally中的代码。
 	3、作用：一般使用关闭资源

代码示例：

```java
import java.util.Scanner;

/**
 * 异常捕获的第二种格式
 */
public class Simple04 {
    public static void main(String[] args) {
        try {
            int i = 1 / new Scanner(System.in).nextInt();
            System.out.println(i);
            return;
        } catch (ArithmeticException e) {
            System.out.println("除零异常发生了");
        } finally {
            System.out.println("一定会执行的代码");
        }
    }
}
```

## 异常处理的第三种格式

1、格式：
 	try {
 	 	可能发生异常的代码
} finally {
 	一定要执行的代码
}
2、作用：
 	1、第三种格式无法捕获和处理异常，一旦发生任何异常，仍然会按照默认的处理方式，一层一层向上抛出，到达jvm，结束虚拟机
 	2、无论try中的语句是否发生异常，finally中的代码都一定有执行的机会
 	3、如果有两句代码，都需要有执行的机会，不希望第一句的成功与否影响到第二句的执行机会，那么就把这两句代码分别放在try和finally中，就是try中你报你的错，我finally中代码该咋执行咋执行。

代码示例：

```java
import java.util.Scanner;
/**
 * 异常处理的第三种格式
 */
public class Simple05 {
    public static void main(String[] args) {
        try {
            System.out.println(1 / new Scanner(System.in).nextInt());
        } finally {
            System.out.println("一定有机会执行的代码");
        }
    }
}
```



# 继承体系中的常用方法

1. 在异常的继承体系中，所有的方法定义在了Throwable这个顶层父类中，子类中几乎没有什么特有方法
2. Throwable中的构造方法：
    	       Throwable()：创建一个没有任何参数的异常对象
        	Throwable(String message)：创建一个带有指定消息的异常对象
        	Throwable(Throwable cause)：创建一个有原因异常的异常对象
3. 常用成员方法：
    	               getMessage()：获取异常的详细信息
                	toString()：获取异常对象的详细信息

代码示例：

```java
import java.util.Scanner;
/**
 * 继承体系中的常用方法
 */
public class Simple06 {
    public static void main(String[] args) {
        test1();
    }

    private static void test1() {
        try {
            System.out.println(1 / new Scanner(System.in).nextInt());
        } catch (ArithmeticException ae) {         
            System.out.println(ae.getMessage());//获取当前异常对象的消息字符串
            System.out.println(ae.toString());//获取当前异常对象的字符串描述
            System.out.println("--------------------------");
            ae.printStackTrace();//获取当前异常对象的方法调用路径
        }
    }
}
```

# throw关键字

1. throw：抛出，用于抛出一个异常对象
3. 作用：
    	创建一个异常对象，使用throw关键字抛出，实现了程序的结束或者跳转
3. 说明：
        1. 如果抛出的是编译时异常，那么这个异常必须使用异常处理的方式处理，才能编译成功
        2. 如果抛出的是运行时异常，在编译阶段就相当于没有异常，可以不处理这个异常

代码示例：

```java
public class Test {
    public static void main(String[] args) {
        try {
            Person p = new Person();
            p.setAge(-10);
            System.out.println(p);
        } catch (RuntimeException e) {
            System.out.println(e.getMessage());
        }
    }
}

class Person {
    private int age;

    public void setAge(int age) {
        if (age < 0) {
            //年龄小于0，这种情况不符合生活正常情况，就将这种情况封装成异常对象
            RuntimeException re = new RuntimeException("年龄非法");
            throw re;//将异常对象抛出，
        }
        this.age = age;
    }
}
```

## throws关键字

1. throws：抛出，用于声明一个异常类型

2. 在某个方法中，有一些编译时异常，没有给出处理的方案，没有捕获这个异常，没有处理这个异常，就说明这个方法是一个有问题的方法。为了让调用者在调用时，可以考虑到处理这个异常，所必须在当前方法的声明上，声明这个异常。

3. 声明格式：
    	修饰符 返回值类型 方法名称(参数列表) throws 异常类型1, 异常类型2,... {
        	 	可能出现异常的代码
   }
   
4. 注意事项：
     1、如果抛出的是一个运行时异常，那么就相当于没有抛出异常，这种异常也不需要在方法上声明；声明了一个运行时异常，也相当于没有做任何声明
         	2、如果抛出的是一个编译时异常，那么就必须进行声明或者捕获；如果声明了一个编译时异常，将来调用这个方法时，也相当于有一个声明的异常。
         	3、在声明异常的时候，尽量声明<小>的异常、尽量声明<少>的异常

     ​				一个方法暴露太多异常，别人不敢调用你了

代码示例：

```java
public class Test {
    public static void main(String[] args) throws Exception {
        try {
            Person p = new Person();
            p.setAge(-10);
            System.out.println(p);
        } catch (RuntimeException e) {
            System.out.println(e.getMessage());
        }
    }
}

class Person {
    private int age;

    public void setAge(int age) throws Exception {
        if (age < 0) {
            Exception exception = new Exception("年龄非法");
            throw exception;//将异常对象抛出，
        }
        this.age = age;
    }
}
```

## throw和throws的比较

1. throw是对异常对象的抛出，throws是对异常类型的声明

2. throw是对异常对象实实在在的抛出，一旦使用了throw关键字，就一定有一个异常对象出现；

   throws是对可能出现的异常类型的声明，即使声明了异常类型，在该方法中，也可能不出现任何异常。

3. throw后面只能跟一个异常对象；

   throws可以跟很多个异常类型






